version: '3'
services:
    phpsst-app:
        build: .
        container_name: phppsst-app
        ports:
            - 80:80
        environment:
            STORAGE: 'redis'
            REDIS_HOST: 'tcp://phppsst-redis:6379'
    phppsst-redis:
        image: redis:7
        container_name: phppsst-redis
